### ISSUE TITLE
Vulnerability : Server-Generated ACAO Header From Client-Specified Origin header

### ISSUE THREAD

**Issue by sgwgsw** [Nano-Core/Nano.Library#84]
https://github.com/Nano-Core/Nano.Library/blob/e2684cdbf249ec719838eef2bee603b20f5c0c53/Nano.Web/Hosting/Middleware/HttpRequestOptionsMiddleware.cs#L25-L35

The client's Origin header is reflected in Access-Control-Allow-Origin header from server. This gives any domain access to the resources. There should be a white-list in the config file that lists allowed origin headers.

The issue is made worse with "Access-Control-Allow-Credentials: true". Now that any domain can access the endpoints, they also can also authenticate as another user. This can be done by sending a crafted link to a user who is logged in - the script would send a CORS request to sensitive endpoints and the browser would send along their cookies since this flag is set to true.

More info on vulnerability - https://portswigger.net/web-security/cors#server-generated-acao-header-from-client-specified-origin-header

**Comment by vivet** [comment]
Hi
Normally I configure the CORS on the web server (ingress), but you are right.

I will look into some better options for configuring this. I am currently working on v8.0, and will see if I can fix it in that release.

**Comment by sgwgsw** [comment]
Understood - I worry that users would leave this as-is, since it's very lax and wouldn't cause errors when testing.

Thank you for your consideration, hope it makes it in to v8.0 :)

**Comment by vivet** [comment]
Though, this is only set for the OPTIONS method.
You can still configure the white-listed domains, but the options endpoint should reflect that.

**Comment by sgwgsw** [comment]
"GET, POST, PUT, PATCH, DELETE," methods don't present those headers from code, just OPTIONS?

**Comment by vivet** [comment]
If you look here https://github.com/Nano-Core/Nano.Library/blob/e2684cdbf249ec719838eef2bee603b20f5c0c53/Nano.Web/Hosting/Middleware/HttpRequestOptionsMiddleware.cs#L20

You can see that these headers are only applied when the method is options.

**Comment by sgwgsw** [comment]
Makes sense.

It could still be worth a fix - I think some may match CORS policy to this one if they need to set up CORS on their instance. They may just see these responses set here and have the server maintain the same configuration to avoid errors/troubleshooting.

Up to you, great project!

**Comment by vivet** [comment]
Yes I will take a look at it

**Comment by vivet** [comment]
I have made a new implementation of CORS. 
You can now configure all the CORS parameters, and those will be exposed in the HTTP OPTIONS response

**Comment by sgwgsw** [comment]
Awesome fix, thanks!
